on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    outputs:
      targets: ${{ steps.build-matrix.outputs.targets }}
    steps:
      - name: Setup Dynamic Build Matrix
        id: build-matrix
        uses: grandcolline/github-actions-sample/.github/actions/matrix-test@main

  execute:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs:
      - setup
    strategy:
      fail-fast: true
      max-parallel: 3
      matrix:
        targets: ${{ fromJSON(needs.setup.outputs.targets) }}
    steps:
      - uses: actions/checkout@v3
      - name: Execute Script
        run: echo "${{ matrix.targets }}"
